name: auto_update
on: 
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    
  
jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:  
          python-version: "3.9"

      - name: "install deps"
        run: pip install -r requirements.txt

      - name: "run updater"
        id: "auto_update"
        run: |
          python3 auto_update.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Create Pull Request
        if: ${{ steps.auto_update.outputs.updated != '' && steps.auto_update.outputs.has_open_pulls }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ steps.auto_update.outputs.updated }}
          title: ${{ steps.auto_update.outputs.updated }}
          body: "automatic update, pleeeeease manually review before accepting\nlook at updated-urls.csv"
